services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: yoga-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    networks:
      - yoga-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: yoga-kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - yoga-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: yoga-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: yoga
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - yoga-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: yoga-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - yoga-network

  postgres-auth:
    image: postgres:15.1-alpine
    container_name: yoga-postgres-auth
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
    networks:
      - yoga-network
  postgres-users:
    image: postgres:15.1-alpine
    container_name: yoga-postgres-users
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
      POSTGRES_DB: users
    volumes:
      - postgres-users-data:/var/lib/postgresql/data
    networks:
      - yoga-network

  postgres-media:
    image: postgres:15.1-alpine
    container_name: yoga-postgres-media
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: media
      POSTGRES_PASSWORD: media
      POSTGRES_DB: media
    volumes:
      - postgres-media-data:/var/lib/postgresql/data
    networks:
      - yoga-network

  redis:
    image: redis:7.2-alpine
    container_name: yoga-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - yoga-network


networks:
  yoga-network:
    driver: bridge

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  postgres-auth-data:
  postgres-users-data:
  postgres-media-data:
  redis-data: